name =  zombies4test
description = A zombie mod that challenges the player to survive in an apocalyptic world.
depends = mobs 
optional_depends =rp_crafting,mcl_mobs,mobs_mc,3d_armor,mcl_armor
author = DuckGo
